// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using stin.Data;

#nullable disable

namespace stin.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("stin.Models.Klient", b =>
                {
                    b.Property<int>("UcetNum")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("UcetNum");

                    b.ToTable("Klienti");
                });

            modelBuilder.Entity("stin.Models.Ucet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Mena")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UcetNum")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("hodnota")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Ucty");
                });
#pragma warning restore 612, 618
        }
    }
}
